"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Container } from "@/components/ui/Container";
import { DashboardHeader } from "@/components/dashboard/DashboardHeader";
import { fetchCertificates, type CertificateRecord, type CourseProgressSummary } from "@/services/certificatesService";
import { showToast } from "@/components/ui/Toast";
import { useDashboardData } from "@/components/dashboard/DashboardDataProvider";

const container = { hidden: {}, show: { transition: { staggerChildren: 0.08 } } };
const item = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

/**
 * Writes a real certificate and hands the browser a file.
 *
 * The button used to show "Certificate downloaded!" and download nothing at all.
 * It claims PDF, so this produces PDF rather than quietly renaming the button to
 * match a text file — a certificate the user prints should not reflow.
 *
 * The PDF is generated by hand because it is a single page of text in a known
 * layout. A PDF library would be a dependency for something this simple, and the
 * alternative — an HTML file called `.pdf` — produces a file that does not open.
 */
function downloadCertificate(cert: CertificateRecord, holder: string): void {
  const escape = (value: string) =>
    value.replace(/([\\()])/g, "\\$1").replace(/[^\x20-\x7e]/g, "");

  // Uncompressed PDF: text is drawn with Tj, so escaping parens and stripping
  // non-ASCII is sufficient and the byte offsets stay computable.
  const stream = `BT /F1 22 Tf 72 720 Td (${escape("Bridge Coach")}) Tj ET\n` +
    `BT /F1 12 Tf 72 660 Td (This certifies that) Tj ET\n` +
    `BT /F1 20 Tf 72 620 Td (${escape(holder || "a learner")}) Tj ET\n` +
    `BT /F1 12 Tf 72 560 Td (has completed) Tj ET\n` +
    `BT /F1 18 Tf 72 520 Td (${escape(cert.title)}) Tj ET\n` +
    `BT /F1 11 Tf 72 470 Td (${escape(cert.description).slice(0, 110)}) Tj ET\n` +
    `BT /F1 10 Tf 72 80 Td (${escape(`Issued ${cert.earnedAt}`)}) Tj ET\n`;

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}endstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${cert.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-certificate.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Revoked after the click, not immediately: Safari can still be reading it.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  showToast("success", "Certificate downloaded");
}

export default function CertificatesPage() {
  // Certificates are EARNED, so they are derived from persisted lesson progress
  // (Sprint 58 §11). The page previously rendered four static certificates as if
  // the user had already earned them.
  const [certificates, setCertificates] = useState<CertificateRecord[]>([]);
  const [inProgress, setInProgress] = useState<CourseProgressSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  // The name printed on the certificate. Taken from the signed-in user so the
  // document names the person who earned it rather than a placeholder.
  const { data: dashboard } = useDashboardData();
  const profileName = dashboard?.user
    ? `${dashboard.user.firstName} ${dashboard.user.lastName ?? ""}`.trim()
    : "";

  useEffect(() => {
    (async () => {
      const result = await fetchCertificates();
      setCertificates(result.data ?? []);
      setInProgress(result.inProgress);
      setLoadError(result.error);
      setLoading(false);
    })();
  }, []);

  return (
    <div className="min-h-screen bg-bg-primary">
      <DashboardHeader />
      <main className="py-8 sm:py-12">
        <Container className="max-w-4xl">
          <motion.div variants={container} initial="hidden" animate="show">
            <motion.h1 variants={item} className="text-2xl font-bold text-text-primary mb-2">Certificates</motion.h1>
            <motion.p variants={item} className="text-sm text-text-tertiary mb-8">
              {loading
                ? "Loading your certificates…"
                : loadError ?? `${certificates.length} certificate${certificates.length === 1 ? "" : "s"} earned so far.`}
            </motion.p>

            <div className="grid gap-6 sm:grid-cols-2">
              {certificates.map((cert) => (
                <motion.div key={cert.id} variants={item} className="group">
                  {/* Certificate preview card */}
                  <div className="relative rounded-xl border border-border bg-bg-card overflow-hidden">
                    {/* Gold seal decoration */}
                    <div className="absolute top-3 right-3 h-14 w-14 rounded-full bg-gradient-to-br from-yellow-400 to-amber-600 flex items-center justify-center shadow-lg opacity-80">
                      <span className="text-xl">🏆</span>
                    </div>

                    {/* Header gradient */}
                    <div className={`bg-gradient-to-r ${cert.gradient} px-6 py-8 relative`}>
                      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.15),transparent_60%)]" />
                      <div className="relative">
                        <p className="text-[10px] uppercase tracking-widest text-white/70 mb-1">Certificate of Completion</p>
                        <h3 className="text-lg font-bold text-white">{cert.title}</h3>
                      </div>
                    </div>

                    {/* Body */}
                    <div className="px-6 py-5">
                      <p className="text-xs text-text-tertiary leading-relaxed mb-4">{cert.description}</p>

                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2 text-xs text-text-secondary">
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
                          </svg>
                          {cert.earnedAt}
                        </div>

                        <button
                          onClick={() => downloadCertificate(cert, profileName)}
                          className="flex items-center gap-1.5 rounded-lg bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary hover:bg-primary/20 transition-all"
                        >
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                          </svg>
                          Download
                        </button>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>

            {/* Empty state if no certificates */}
            {certificates.length === 0 && !loading && (
              <motion.div variants={item} className="text-center py-20">
                <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-bg-secondary">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-text-tertiary">
                    <path d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" />
                  </svg>
                </div>
                <p className="text-sm text-text-tertiary">No certificates yet.</p>
                <p className="text-xs text-text-tertiary mt-1">Complete courses to earn your first certificate.</p>
              </motion.div>
            )}
          </motion.div>
        </Container>
      </main>
    </div>
  );
}
