import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Target,
  Zap,
  Flame,
  Star,
  Clock,
  BarChart3,
  Calendar,
  CreditCard,
  Award,
  Medal,
  Gift,
  Play,
  FileText,
  Activity,
  Sparkles,
  Bell,
  Hand,
  HelpCircle,
  AlertCircle,
  Brain,
  Dumbbell,
  Crown,
  Pin,
  Scissors,
  Mail,
  Check,
  X,
  AlertTriangle,
  Lock,
  Unlock,
  Link,
  Coins,
} from "lucide-react";

export function emojiToIcon(emoji: string): LucideIcon | null {
  const map: Record<string, LucideIcon> = {
    "📖": BookOpen,
    "📚": BookOpen,
    "🎯": Target,
    "⚡": Zap,
    "🔥": Flame,
    "⭐": Star,
    "🌟": Star,
    "⏱": Clock,
    "⏱️": Clock,
    "📊": BarChart3,
    "📅": Calendar,
    "🃏": CreditCard,
    "🏆": Award,
    "🥇": Award,
    "🥈": Medal,
    "🥉": Medal,
    "🎉": Star,
    "🎁": Gift,
    "🎬": Play,
    "📄": FileText,
    "💬": Activity,
    "✨": Sparkles,
    "🔔": Bell,
    "👋": Hand,
    "❓": HelpCircle,
    "❗": HelpCircle,
    "💡": AlertCircle,
    "🧠": Brain,
    "💪": Dumbbell,
    "👑": Crown,
    "📌": Pin,
    "✂": Scissors,
    "✉": Mail,
    "✔": Check,
    "✅": Check,
    "✗": X,
    "❌": X,
    "⚠️": AlertTriangle,
    "🔒": Lock,
    "🔓": Unlock,
    "🔗": Link,
    "💰": Coins,
    "🪙": Coins,
  };
  return map[emoji] ?? null;
}
