import type { LucideIcon } from "lucide-react";

export function emojiToIcon(emoji: string): LucideIcon | null {
  const map: Record<string, LucideIcon> = {
    "📖": require("lucide-react").BookOpen,
    "📚": require("lucide-react").BookOpen,
    "🎯": require("lucide-react").Target,
    "⚡": require("lucide-react").Zap,
    "🔥": require("lucide-react").Flame,
    "⭐": require("lucide-react").Star,
    "🌟": require("lucide-react").Star,
    "⏱": require("lucide-react").Clock,
    "⏱️": require("lucide-react").Clock,
    "📊": require("lucide-react").BarChart3,
    "📅": require("lucide-react").Calendar,
    "🃏": require("lucide-react").CreditCard,
    "🏆": require("lucide-react").Award,
    "🥇": require("lucide-react").Award,
    "🥈": require("lucide-react").Medal,
    "🥉": require("lucide-react").Medal,
    "🎉": require("lucide-react").Star,
    "🎁": require("lucide-react").Gift,
    "🎬": require("lucide-react").Play,
    "📄": require("lucide-react").FileText,
    "💬": require("lucide-react").Activity,
    "✨": require("lucide-react").Sparkles,
    "🔔": require("lucide-react").Bell,
    "👋": require("lucide-react").Hand,
    "❓": require("lucide-react").HelpCircle,
    "❗": require("lucide-react").HelpCircle,
    "💡": require("lucide-react").AlertCircle,
    "🧠": require("lucide-react").Brain,
    "💪": require("lucide-react").Dumbbell,
    "👑": require("lucide-react").Crown,
    "📌": require("lucide-react").Pin,
    "✂": require("lucide-react").Scissors,
    "✉": require("lucide-react").Mail,
    "✔": require("lucide-react").Check,
    "✅": require("lucide-react").Check,
    "✗": require("lucide-react").X,
    "❌": require("lucide-react").X,
    "⚠️": require("lucide-react").AlertTriangle,
    "🔒": require("lucide-react").Lock,
    "🔓": require("lucide-react").Unlock,
    "🔗": require("lucide-react").Link,
    "💰": require("lucide-react").Coins,
    "🪙": require("lucide-react").Coins,
  };
  return map[emoji] ?? null;
}
